### ISSUE TITLE
Di Buat Branch untuk tiap versi

### ISSUE THREAD

**Issue by haifahrul** [ImmanuelJL/prestashop-ongkir-mycarrier_rj#1]
Dear mas bro,

Lebih baik jangan di bikin file Zip. Alangkah baiknya di buka source nya jadi teman-teman lain bisa contribute langsung tanpa extract dan zip file nya.

Jadi nanti bisa di buat per branch per versi 1.6 dan 1.7.

Yang di taro di master branch version latest aja yaitu versi 1.7.

Harapannya biar teman-teman lain bisa contribute dan meningkatkan modules ini

**Comment by ImmanuelJL** [comment]
Dear Mas Bro,
Thanks untuk masukannya ya, di buat seperti yang mas sebutkan di atas ada baiknya juga untuk keperluan development ke depannya.

**Comment by haifahrul** [comment]
Dear @ImmanuelJL 

Iya bro, btw. module ini untuk versi prestashop 1.6 atau 1.7 atau keduanya?
Karena saya lihat di blog module [versi 1.6](https://immanueljl.blogspot.com/2017/08/module-hitung-ongkir-jne-tiki-pos.html) dan [versi 1.7](https://immanueljl.blogspot.com/2018/07/module-hitung-ongkir-jne-tiki-pos.html) mengarah ke repo yang sama. 

Module ini kalau di jalankan di prestashop versi 1.6 bisa jalan juga kah? Saya belum coba mas hehe

Ini di open lagi aja mas, soalnya kan belum solved.
