### ISSUE TITLE
Tidak Ada Menu Untuk Ubah Tipe Akun Rajaongkir.com

### ISSUE THREAD

**Issue by haifahrul** [ImmanuelJL/prestashop-ongkir-mycarrier_rj#3]
Kedepannya lebih baik kita buatkan untuk tipe akun di raja ongkir :
1. starter
2. basic
3. pro

kita buatkan form untuk isi tipe akun tersebut.

**Comment by ImmanuelJL** [comment]
Ide bagus mas, boleh juga di buatkan untuk tipe akunnya

**Comment by haifahrul** [comment]
Jangan di close dulu mas, kan belum dibuat :-D . Biar jadi pengingat kalau fitur ini belum dibuat . 
Di open lagi aja issue ini.
