### ISSUE TITLE
Select Box City untuk Costumer Tidak Mucul nama Kota

### ISSUE THREAD

**Issue by efandi07** [ImmanuelJL/prestashop-ongkir-mycarrier_rj#4]
Terimakasih Untuk Pengembang Modul karna sangat berguna untuk saya yang lagi mencoba beljar untuk cms prstashop . tapi untuk modul prestahop-ongkir-mycarrier-rj setelah saya instal di prestahop saya untuk select box city tidak ada nama kota yang muncul ketika saya klik. mohon Kiranya ada waktu untuk membalas , 
![upload togithub](https://user-images.githubusercontent.com/44107006/46900886-efb77880-ced3-11e8-8b3a-5e5b1bb0eebb.png)
Terima Kasih

**Comment by haifahrul** [comment]
@efandi07 pakai versi prestashop berapa?

**Comment by efandi07** [comment]
pakai prestashop 1.7.4.2 pak

**Comment by haifahrul** [comment]
udah coba replace file [CustomerAddressFormatter.php](https://github.com/ImmanuelJL/prestashop-ongkir-mycarrier_rj/blob/master/mycarrier_rj/controllers/front/CustomerAddressFormatter.php) ?

@ImmanuelJL need help

**Comment by efandi07** [comment]
Terimkasih sudah membalas pak , sudh saya replace dan untuk nama kota sudah ada hanya masalah datang lagi di biaya shipping free semua pak , ada solusi lagi pak 
![upglin](https://user-images.githubusercontent.com/44107006/47419503-8f171e00-d7a6-11e8-8ac5-3e424bba0c14.png) saya sangat berterima kasih, karna bapak sudah sempat membalas issue saya.

**Comment by efandi07** [comment]
sudah saya clear chace serta saya install ulang lagi untuk modulnya, tapi masih free juga , untuk key city sudh saya tempatkan di jakarta pusat serta saya tes untuk kirim ke daerah semarang tapi masih free juga pak ,

**Comment by haifahrul** [comment]
Coba alamat lain, misal daerah bogor. Bisa jadi tujuannya tidak valid atau originnya tidak valid. Bisa coba test pakai API nya rajaongkir via postman.

**Comment by efandi07** [comment]
Terimakasih Pak, kemarin saya coba untuk ganti tujuan dan ganti oroginnya juga pak tapi hasil ttp sama masih free untuk semua pak, ada saran lain pak ? replace script mycarrier_rj.php juga sudh saya coba pak tapi masih belum menyelesaikan masalah pak ,

**Comment by ayulistianto** [comment]
Sama masalahnya, semua pengiriman free ... sudah di coba pakai postman apinya jalan gan.. cache udh d hapus tp ttp aja free...

**Comment by haifahrul** [comment]
Ada yang bisa bantu fix bug? Belum sempat check code issue ini.

Pada tanggal Rab, 31 Okt 2018 10.37 ayulistianto <notifications@github.com
menulis:

**Comment by ayulistianto** [comment]
Saya pake PS 1.7.4.2, untuk kotanya sudah muncul pake selectbox tetapi setelah pilih kota ongkir jd free semua. Tadi cek api raja ongkir nya bener, udh d coba pake postman bisa..

**Comment by zdifahk** [comment]
mohon ijin gabung mastah.. tolong sekiranya di share yang mengubah ongkir dari free
