### ISSUE TITLE
Error Install di PS 1.6

### ISSUE THREAD

**Issue by dionwisnu** [ImmanuelJL/prestashop-ongkir-mycarrier_rj#5]
Misi Gan,
saya mau coba install modul di PS 1.6 tapi muncul error seperti ini.
![error install custom](https://user-images.githubusercontent.com/9894938/47065935-cf0e5c00-d20e-11e8-9a96-49417ff5f152.png)

**Comment by haifahrul** [comment]
@ImmanuelJL ada ide mas? apa ini repo untuk versi 1.7?
