### ISSUE TITLE
Biaya pengiriman free semua. Pemilihan kota sudah menggunakan selectbox, cache sudah dihapus tetapi biaya pengiriman tetap free..

### ISSUE THREAD

**Issue by ayulistianto** [ImmanuelJL/prestashop-ongkir-mycarrier_rj#6]

**Comment by ayulistianto** [comment]
saya tadi coba2 cek kynya salah di penamaan kota. Kota $toCity gak ketemu idnya karena ada kata kabupaten contoh (Kabupaten Cilacap), harusnya Cilacap saja tanpa kata kabupaten. Karena ada kata kabupaten jd gak cocok saat d cari idnya.. Saya ga bisa ngeditnya. Gak terlalu paham PS, cuma paham phpnya aja..  mohon d cek lagi bang

**Comment by ayulistianto** [comment]
ubah value selectbox, hilangkan kata kabupaten.
Di line 140 file  /override/classes/form/CustomerAdressFormatter.php
foreach ($responseCity->rajaongkir->results as $city) {
                    $formField->addAvailableValue(
                        $city->type . ' ' . $city->city_name,
                        $city->city_name . ' (' . $city->type . ')'
                    );
                }

HAPUS $city->type.' '.

HASILNYA
foreach ($responseCity->rajaongkir->results as $city) {
                    $formField->addAvailableValue(
                        $city->city_name,
                        $city->city_name . ' (' . $city->type . ')'
                    );
                }

Berhasil keluar biayanya. Tapi kenapa yang muncul cuma 5 pilihan bang? padalah di catalog produk pengiriman d pilih semua seperti jne yes, tiki ons, dll, tp ada beberapa yg ga muncul atau yg ga muncul itu emg ga terjangkau oleh kurir?

![capture](https://user-images.githubusercontent.com/44629172/47842961-be560c80-ddf0-11e8-9f9a-75eaeed86314.PNG)

**Comment by ayulistianto** [comment]
satu lagi kynya itu weightnya masih dalam bentuk kg.. d raja ongkir pakenya gram.. tadi tak cek biaya d web saya sama d raja ongkir beda .

**Comment by haifahrul** [comment]
Kalau widgetnya itu, setting di prestashopnya, by default di prestashop itu
Kg, kamu setting dulu saja ganti ke gram

Best Regards,
Ahmad Fakhrurozi Syah
Web Developer

*WA: *+62857-1056-8571  |  *Mobile: *+62812-9919-7868
*LinkedIn: *id.linkedin.com/ <http://id.linkedin.com/in/ahmadfakhrurozisyah>
*in/haifahrul/*
*Website: *afsyah.com
*Github: *github.com/haifahrul

**Comment by wiakso** [comment]
ternyata issue limit 5 kurir sudah ada di sini?
apakah sudah menemukan solusi bro?
barangkali berkenan boleh dishare kembali hehehe....
terimakasih..

**Comment by ayulistianto** [comment]
Kynya itu dr raja ongkirnya gan.. coba aja d cek biaya ongkir langsung dr web rajaongkir.. input kota dan tujuannya sama ky yg ps,

**Comment by haifahrul** [comment]
Ini dibuat pakai api rajaongkir starter (gratis), terdapat limit.

https://bitbucket.org/haifahrul/jasindo-mobile-app/admin
![image](https://user-images.githubusercontent.com/6553704/48700977-f7c7ae00-ec1f-11e8-9dbe-85459b64aa77.png)

Jadi kalau mau banyak, harus beli dulu lisensinya, terus sedikit custom di core plugin ini.

Harusnya sih dibuat flexible, bisa ganti tipe akun raja ongkir dan update lisensi via UI (ga perlu coding lagi)

**Comment by haifahrul** [comment]
> ubah value selectbox, hilangkan kata kabupaten.
> Di line 140 file /override/classes/form/CustomerAdressFormatter.php
> foreach ($responseCity->rajaongkir->results as $city) {
> $formField->addAvailableValue(
> $city->type . ' ' . $city->city_name,
> $city->city_name . ' (' . $city->type . ')'
> );
> }
> 
> HAPUS $city->type.' '.
> 
> HASILNYA
> foreach ($responseCity->rajaongkir->results as $city) {
> $formField->addAvailableValue(
> $city->city_name,
> $city->city_name . ' (' . $city->type . ')'
> );
> }
> 
> Berhasil keluar biayanya. Tapi kenapa yang muncul cuma 5 pilihan bang? padalah di catalog produk pengiriman d pilih semua seperti jne yes, tiki ons, dll, tp ada beberapa yg ga muncul atau yg ga muncul itu emg ga terjangkau oleh kurir?
> 
> ![capture](https://user-images.githubusercontent.com/44629172/47842961-be560c80-ddf0-11e8-9f9a-75eaeed86314.PNG)

Bisa di fork repo ini, lalu fixing bug yang tadi kamu benerin itu, lalu pull request mas, biar module ini lebik baik hehe

**Comment by diiadisaputra94** [comment]
puya ane kok masih gratis ya ongkirnya
