### ISSUE TITLE
Hanya menampilkan 5 jenis shipping

### ISSUE THREAD

**Issue by wiakso** [ImmanuelJL/prestashop-ongkir-mycarrier_rj#7]
Halo,
apakah sudah ada yang implementasi modul ini dengan sempurna?
saya telah mencoba di Prestashop 1.7.4.3 dan mengalami kendala tampilan pada pilihan kurir hanya 5.
sampai saat ini blm menemukan jalan keluar.
barangkali bisa membantu saya ucapkan terimakasih sebelumnya...

**Comment by wiakso** [comment]
![kurir](https://user-images.githubusercontent.com/45158878/48687556-7f97c300-ebf4-11e8-88f1-d723527b7f9e.png)

menambahkan screenshot

**Comment by ayulistianto** [comment]
kynya itu dr rajaongkir gan, coba aja cek langsung d web rajaongkir.. masukan asal dan tujuannya sama dg yg d ps, mungkin untuk daerah tertentu tidak bisa dijangkau. Coba ganti daerahnya, ada yg muncul semua, ada yg cuma muncul 5.

**Comment by wiakso** [comment]
bener gan... pas banget yang ane test 2 kota sama2 cuma 5...
giliran test kota besar bisa keluar banyak... hehehe...

**Comment by haifahrul** [comment]
Iya bro, ini pakai yang starter, tapi kalau beli license yang pro kayaknya bisa sampai level kelurahan deh, saya juga belum coba pakai yang versi pro atau starter
